# Generated by Django 5.2.7 on 2025-11-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
